# Generated by Django 5.1.4 on 2026-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery'), ('UPI_MANUAL', 'UPI Manual')], default='UPI', max_length=20),
        ),
    ]
